In [ ]:
import pandas as pd
df = pd.read_csv('/content/EDA_census.csv')
df = df.dropna(axis=1)
df.describe()

,State_Code,Distt_Code,T_Persons,T_Males,T_Females,IL_Persons,IL_Males,IL_Females,L_Persons,L_Males,L_Females
count,3132.000000,3132.0,3.132000e+03,3.132000e+03,3.132000e+03,3.132000e+03,3.132000e+03,3.132000e+03,3.132000e+03,3.132000e+03,3.132000e+03
mean,17.500000,0.0,3.092861e+06,1.592006e+06,1.500855e+06,1.142315e+06,4.814984e+05,6.608162e+05,1.950546e+06,1.110507e+06,8.400388e+05
std,10.389954,0.0,2.882232e+07,1.483375e+07,1.398926e+07,1.150330e+07,4.966519e+06,6.565306e+06,1.791240e+07,1.023041e+07,7.689529e+06
min,0.000000,0.0,6.000000e+00,4.000000e+00,2.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.750000,0.0,2.141225e+04,1.116850e+04,1.014875e+04,3.453750e+03,1.371500e+03,1.957500e+03,1.296200e+04,7.055250e+03,5.883250e+03
50%,17.500000,0.0,2.389940e+05,1.232525e+05,1.166540e+05,3.054300e+04,1.267350e+04,1.743800e+04,1.319095e+05,8.090150e+04,5.604350e+04
75%,26.250000,0.0,1.123899e+06,5.782720e+05,5.429365e+05,2.291725e+05,8.404050e+04,1.411090e+05,7.046172e+05,4.018530e+05,3.060520e+05
max,35.000000,0.0,1.210855e+09,6.232703e+08,5.875847e+08,4.472162e+08,1.885066e+08,2.587095e+08,7.636388e+08,4.347636e+08,3.288752e+08

In [ ]:
df.head()

,State_Code,Distt_Code,Area_Name,T/R/U,Age_Grp,T_Persons,T_Males,T_Females,IL_Persons,IL_Males,IL_Females,L_Persons,L_Males,L_Females
0,0,0,INDIA,Total,All ages,1210854977,623270258,587584719,447216165,188506636,258709529,763638812,434763622,328875190
1,0,0,INDIA,Total,0-6,164515253,85752254,78762999,164515253,85752254,78762999,0,0,0
2,0,0,INDIA,Total,7,24826640,12903364,11923276,6748214,3388683,3359531,18078426,9514681,8563745
3,0,0,INDIA,Total,8,26968373,14061937,12906436,4131414,2013742,2117672,22836959,12048195,10788764
4,0,0,INDIA,Total,9,23424638,12214985,11209653,2491904,1198339,1293565,20932734,11016646,9916088

In [ ]:
IL_Females = df.loc[((df['Age_Grp'] == '20-24') & (df['Area_Name'] == 'INDIA') & (df['T/R/U'] == 'Total')), 'IL_Females']

Total_Females = df.loc[((df['Age_Grp'] == '20-24') & (df['Area_Name'] == 'INDIA') & (df['T/R/U'] == 'Total')), 'T_Females']

print(IL_Females)
print(Total_Females)

15    12212466
Name: IL_Females, dtype: int64
15    53839529
Name: T_Females, dtype: int64

In [ ]:
per_IL = IL_Females/Total_Females*100
print(per_IL)

15    22.683085
dtype: float64